In [33]:
import pandas as pd

In [34]:
file_path = r"C:/Users/80768/Desktop/Document/找工/Python/PCA/heart.csv"
df = pd.read_csv(file_path)
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [15]:
pip install scipy

Requirement already satisfied: scipy in c:\users\80768\anaconda3\lib\site-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in c:\users\80768\anaconda3\lib\site-packages (from scipy) (1.24.3)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import numpy as np
from scipy import stats

# Remove outliers using Z-score
numeric_cols = df.select_dtypes(include=[float, int]).columns



df = df[(abs(stats.zscore(df[numeric_cols])) < 3).all(axis=1)]

df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130,283,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138,214,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,1,0,1,0,0,1

In [38]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Label encoding for binary categorical columns
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['ExerciseAngina'] = label_encoder.fit_transform(df['ExerciseAngina'])

# One-hot encoding for other categorical columns
df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'], drop_first=True)

# Display the first few rows of the updated dataframe
df.head()

C:\Users\80768\AppData\Local\Temp\ipykernel_27260\3633014240.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = label_encoder.fit_transform(df['Sex'])
C:\Users\80768\AppData\Local\Temp\ipykernel_27260\3633014240.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ExerciseAngina'] = label_encoder.fit_transform(df['ExerciseAngina'])

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130,283,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138,214,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,1,0,1,0,0,1

In [45]:
from sklearn.preprocessing import StandardScaler

# Separating features and target variable
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

# Applying scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Display the scaled features
X_scaled[:5]

array([[-1.42397733,  0.517869  ,  0.47350677,  0.85247445, -0.5526601 ,
         1.3837676 , -0.81343853, -0.86155609,  2.04910478, -0.53877246,
        -0.22819072,  0.80772295, -0.48801799, -1.00338029,  1.12856426],
       [-0.46960954, -1.93099027,  1.65230129, -0.16676927, -0.5526601 ,
         0.751432  , -0.81343853,  0.17249732, -0.48801799,  1.85607112,
        -0.22819072,  0.80772295, -0.48801799,  0.9966311 , -0.88608158],
       [-1.74209992,  0.517869  , -0.11589048,  0.79636929, -0.5526601 ,
        -1.54078457, -0.81343853, -0.86155609,  2.04910478, -0.53877246,
        -0.22819072, -1.23804828,  2.04910478, -1.00338029,  1.12856426],
       [-0.57565041, -1.93099027,  0.35562732,  0.15115996, -0.5526601 ,
        -1.14557481,  1.22934919,  0.68952403, -0.48801799, -0.53877246,
        -0.22819072,  0.80772295, -0.48801799,  0.9966311 , -0.88608158],
       [ 0.06059478,  0.517869  ,  1.06290403, -0.02650637, -0.5526601 ,
        -0.59228116, -0.81343853, -0.86155609, -0.48801799,  1.85607112,
        -0.22819072,  0.80772295, -0.48801799, -1.00338029,  1.12856426]])

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize the models
svm = SVC()
log_reg = LogisticRegression()
rf = RandomForestClassifier()

# Train and evaluate SVM
svm.fit(X_train, y_train)
svm_predictions = svm.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_predictions)

# Train and evaluate Logistic Regression
log_reg.fit(X_train, y_train)
log_reg_predictions = log_reg.predict(X_test)
log_reg_accuracy = accuracy_score(y_test, log_reg_predictions)

# Train and evaluate Random Forest
rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)

# Display the accuracy of each model
svm_accuracy, log_reg_accuracy, rf_accuracy

(0.8820224719101124, 0.8651685393258427, 0.8932584269662921)

In [47]:
from sklearn.decomposition import PCA

# Apply PCA to reduce dimensions
pca = PCA(n_components=0.95)  # Retain 95% of variance
X_pca = pca.fit_transform(X_scaled)

# Split the PCA-transformed data into training and testing sets
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Train and evaluate SVM with PCA
svm.fit(X_train_pca, y_train_pca)
svm_predictions_pca = svm.predict(X_test_pca)
svm_accuracy_pca = accuracy_score(y_test_pca, svm_predictions_pca)

# Train and evaluate Logistic Regression with PCA
log_reg.fit(X_train_pca, y_train_pca)
log_reg_predictions_pca = log_reg.predict(X_test_pca)
log_reg_accuracy_pca = accuracy_score(y_test_pca, log_reg_predictions_pca)

# Train and evaluate Random Forest with PCA
rf.fit(X_train_pca, y_train_pca)
rf_predictions_pca = rf.predict(X_test_pca)
rf_accuracy_pca = accuracy_score(y_test_pca, rf_predictions_pca)

# Display the accuracy of each model with PCA
svm_accuracy_pca, log_reg_accuracy_pca, rf_accuracy_pca

(0.8876404494382022, 0.8595505617977528, 0.8876404494382022)